### ISSUE TITLE
Inadequate documentation

### ISSUE THREAD

**Issue by m-brooks** [chemodax/EditorConfigGuidelines#4]
This looks like a very useful feature, but the only documentation that I can find is the content of the README file. This is not sufficient to explain all the valid options for the new guideline property. If you could document the valid values for the (three?) attributes of each guideline (the first is clearly the column position, but even that needs to convey whether the first column is numbered 0 or 1 and whether the line is drawn on the left hand or right hand edge of the column), I am sure developers would be much more inclined to use this extension. 
It would be a shame for this not to be adopted as widely as possible after all the work that you must have put into it, merely on account of one more hour to produce helpful documentation.

**Comment by sergey-raevskiy** [comment]
+1. Need more examples in README.md!

**Comment by wassim-azi** [comment]
## Guideline Positions and Styles

To configure column guidelines, use the `guidelines` property in your `.editorconfig` file with the following syntax:

- **Syntax:** `guidelines = <column> <style>, <column> <style>, ...`
- **Parameters:**
  - `<column>`: The column number where the guideline should appear.
  - `<style>`: The line style, which can be one of the following:
    - `solid`
    - `dashed`
    - `dotted`

## Example
```ini
[*.cs]
guidelines = 80 solid, 100 dashed, 120 dotted

**Comment by chemodax** [comment]
@johnson-brown Thanks! Added documentation to README.md.

**Comment by m-brooks** [comment]
Folks, good effort as far as it goes, but still falls a little short of what is needed. In the section "Guideline positions and styles" we need to enhance as follows:

- Parameters:
  - `<column>`: The column number where the guideline should appear. Columns are numbered from left to right starting at 0, with the guideline drawn on the specified column's left edge.
  - `<style>`: The line style, which can be one of the following:
    - `solid`
    - `dashed`
    - `dotted`

**Comment by chemodax** [comment]
> Folks, good effort as far as it goes, but still falls a little short of what is needed. In the section "Guideline positions and styles" we need to enhance as follows:
> 
>     * Parameters:
>       
>       * `<column>`: The column number where the guideline should appear. Columns are numbered from left to right starting at 0, with the guideline drawn on the specified column's left edge.
>       * `<style>`: The line style, which can be one of the following:
>         
>         * `solid`
>         * `dashed`
>         * `dotted`
Looks good to me. Updated README.md in c579b10506110da242ad1affb82743b1ba4fcd67.

Please let me know if anything else can be improved in this area.

Thanks!

**Comment by m-brooks** [comment]
Actually I did think of a more concise way of expressing this information, and I edited my previous post accordingly, but the vagaries of github are such that it emailed out a notification with the original text, and the update got missed. 
If you have the time and inclination, the update is an improvement, but if not then what's there is adequate, thanks.

**Comment by chemodax** [comment]
@m-brooks You are right -- I just copied your text from email and I didn't noticed updated text in GitHub issue. I updated text in e105b037e8d15582dca1fb5358dcda8fad7c4b36. I decided to use one-based indexes for columns in text: Visual Studio seems to be using one-based indexes for lines and column, so I think one-based indexes will be easier to understand for Visual Studio users.
